[SERVICE]
    Flush        5
    Daemon       off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /logs/app.json
    Parser            json
    Tag               docker.app
    Refresh_Interval  5
    Skip_Empty_Lines  On
    DB                /tmp/app-docker.db

[FILTER]
    Name record_modifier
    Match docker.app
    Record hostname ${HOSTNAME}
    Record container docker
    Record environment production
    Record source sample_logging_app

[OUTPUT]
    Name    forward
    Match   docker.app
    Host    ${CENTRAL_SERVER}
    Port    24224

[OUTPUT]
    Name    http
    Match   docker.app
    Host    ${CENTRAL_SERVER}
    Port    8888
    URI     /
    Format  json